# 20240312筆記

## 複習萌典API的使用

https://github.com/g0v/moedict-webkit

In [1]:
import requests

In [2]:
# 字串相加 - 01
word = "教室"
url = "https://www.moedict.tw/uni/" + word

In [5]:
url

'https://www.moedict.tw/uni/教室'

In [6]:
# 字串相加 - 02
word = "教室"
url = f"https://www.moedict.tw/uni/{word}"

In [7]:
url

'https://www.moedict.tw/uni/教室'

In [8]:
r = requests.get(url, verify=False)

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [4]:
print(r.text)

	{
		"heteronyms": [
			{
				"bopomofo": "ㄐㄧㄠˋ ㄕˋ",
				"bopomofo2": "jiàu shr̀",
				"definitions": [
					{
						"def": "學校裡進行教學活動的房間。",
						"example": [
							"如：「實驗教室」、「音樂教室」。"
						],
						"synonyms": "課堂,講堂"
					}
				],
				"pinyin": "jiào shì"
			}
		],
		"title": "教室"
	}


In [13]:
r.headers

{'Date': 'Tue, 12 Mar 2024 01:24:45 GMT', 'Content-Type': 'application/json; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Last-Modified': 'Sun, 17 Feb 2013 21:20:12 GMT', 'ETag': 'W/"5121498c-174"', 'Access-Control-Allow-Origin': '*', 'Access-Control-Max-Age': '31536000', 'Strict-Transport-Security': 'max-age=0; preload', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=Crx0GX41qeU8jJcVNHOtQTesLRkzsUyGNN9Yrc6xSwfjUJHLhuq8A8roposGCULboOFaTf2WachrMQH%2F1VQpsD0Oo5XfDce04U%2FczCSCAJSk68%2FUFZiOL5S2glyEh2rLbOPXjXvrzEUQ%2Blxq"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '862ffc886e7717e4-SJC', 'Content-Encoding': 'br'}

In [14]:
data = r.json()

In [15]:
data

{'heteronyms': [{'bopomofo': 'ㄐㄧㄠˋ ㄕˋ',
   'bopomofo2': 'jiàu shr̀',
   'definitions': [{'def': '學校裡進行教學活動的房間。',
     'example': ['如：「實驗教室」、「音樂教室」。'],
     'synonyms': '課堂,講堂'}],
   'pinyin': 'jiào shì'}],
 'title': '教室'}

In [21]:
data['heteronyms']

[{'bopomofo': 'ㄐㄧㄠˋ ㄕˋ',
  'bopomofo2': 'jiàu shr̀',
  'definitions': [{'def': '學校裡進行教學活動的房間。',
    'example': ['如：「實驗教室」、「音樂教室」。'],
    'synonyms': '課堂,講堂'}],
  'pinyin': 'jiào shì'}]

In [22]:
data['heteronyms'][0]

{'bopomofo': 'ㄐㄧㄠˋ ㄕˋ',
 'bopomofo2': 'jiàu shr̀',
 'definitions': [{'def': '學校裡進行教學活動的房間。',
   'example': ['如：「實驗教室」、「音樂教室」。'],
   'synonyms': '課堂,講堂'}],
 'pinyin': 'jiào shì'}

In [23]:
data['heteronyms'][0]['definitions']

[{'def': '學校裡進行教學活動的房間。',
  'example': ['如：「實驗教室」、「音樂教室」。'],
  'synonyms': '課堂,講堂'}]

In [26]:
data['heteronyms'][0]['definitions'][0]

{'def': '學校裡進行教學活動的房間。', 'example': ['如：「實驗教室」、「音樂教室」。'], 'synonyms': '課堂,講堂'}

In [27]:
data['heteronyms'][0]['definitions'][0]['def']

'學校裡進行教學活動的房間。'

## 複習縮排

In [28]:
for i in range(3):
    print("程式區塊開始!")
    print(i)
    print("程式區塊結束!")

程式區塊開始!
0
程式區塊結束!
程式區塊開始!
1
程式區塊結束!
程式區塊開始!
2
程式區塊結束!


In [29]:
for i in range(3):
    print("程式區塊開始!")
    print(i)
print("程式區塊結束!")

程式區塊開始!
0
程式區塊開始!
1
程式區塊開始!
2
程式區塊結束!


In [30]:
for i in range(3):
print("程式區塊開始!")
print(i)
print("程式區塊結束!")

IndentationError: expected an indented block after 'for' statement on line 1 (731320291.py, line 2)

## gradio使用簡介

In [ ]:
!pip install gradio

In [31]:
import gradio as gr

In [32]:
def lookup(word):
    url = f"https://www.moedict.tw/uni/{word}"
    # r = requests.get(url, verify=False)
    # data = r.json()
    data = requests.get(url, verify=False).json()
    return data['heteronyms'][0]['definitions'][0]['def']

In [33]:
lookup('公司')

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


'依公司法登記成立的社團法人營利企業組織。可分無限公司、有限公司、股份有限公司、兩合公司、股份兩合公司等五類。'

In [34]:
gr.Interface(lookup, "text", "text").launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\victor

In [35]:
gr.Interface(lookup, "text", "text", title="國語辭典").launch()

Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.


In [36]:
def lookup(word):
    try:
        url = f"https://www.moedict.tw/uni/{word}"
        data = requests.get(url, verify=False).json()
        return data['heteronyms'][0]['definitions'][0]['def']
    except Exception:
        return "資料查詢錯誤！可能是查不到該名詞！"

In [37]:
gr.Interface(lookup, "text", "text", title="國語辭典").launch()

Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.


C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [38]:
gr.Interface(lookup, "text", "text", title="國語辭典").launch(share=True)

Running on local URL:  http://127.0.0.1:7863

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.


## OpenStreetMap Geocoding API 使用練習

https://nominatim.org/release-docs/develop/api/Search/

In [41]:
place = "高雄市"
url = f"https://nominatim.openstreetmap.org/search?format=json&q='{place}'"

In [42]:
data = requests.get(url, verify=False).json()

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nominatim.openstreetmap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [43]:
data

[{'place_id': 237395083,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 2127079,
  'lat': '22.6203348',
  'lon': '120.3120375',
  'class': 'boundary',
  'type': 'administrative',
  'place_rank': 8,
  'importance': 0.5951571765063468,
  'addresstype': 'city',
  'name': '高雄市',
  'display_name': '高雄市, 臺灣',
  'boundingbox': ['10.3447222', '23.4716871', '114.3072222', '121.0490355']}]

In [45]:
data[0]['lat']

'22.6203348'

In [46]:
data[0]['lon']

'120.3120375'

In [50]:
def place2gps(place):
    url = f"https://nominatim.openstreetmap.org/search?format=json&q='{place}'"
    data = requests.get(url, verify=False).json()
    return float(data[0]['lat']), float(data[0]['lon'])

In [51]:
place2gps('高雄市')

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nominatim.openstreetmap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


(22.6203348, 120.3120375)

## 使用上面的geocoding函式，配合folium畫地圖

In [52]:
import folium

In [59]:
folium.Map(place2gps('台灣康寧'), zoom_start=16)

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nominatim.openstreetmap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [63]:
place = "高雄流行音樂中心"
gps = place2gps(place)
m = folium.Map(gps, zoom_start=16)
folium.Marker(gps, popup=place).add_to(m)
m

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nominatim.openstreetmap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [64]:
def place2gps(place):
    try:
        url = f"https://nominatim.openstreetmap.org/search?format=json&q='{place}'"
        data = requests.get(url, verify=False).json()
        return float(data[0]['lat']), float(data[0]['lon'])
    except Exception:
        return None

In [69]:
place = "澄清湖"
gps = place2gps(place)
if gps:
    m = folium.Map(gps, zoom_start=16)
    folium.Marker(gps, popup=place).add_to(m)
else:
    m = folium.Map()
m

C:\Users\victor\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nominatim.openstreetmap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [70]:
x = None

In [71]:
bool(x)

False

# Python資料分析簡介

* NumPy ==> 科學運算基礎套件
* MatPlotLib ==> 繪圖基礎套件
* Pandas ==> 資料分析基礎套件

套件載入慣例：
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

<pre>
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```
</pre>

## NumPy (Numerical Python)

* ndarray (N-Dimensional Arrays)
* ufunc (Universal Functions)

### 為什麼需要Numpy？

In [72]:
x = [1, 2, 3]
y = [4, 5, 6]

In [73]:
x + y

[1, 2, 3, 4, 5, 6]

In [74]:
2 * x

[1, 2, 3, 1, 2, 3]

In [75]:
import numpy as np

In [76]:
x1 = np.array(x)
y1 = np.array(y)

In [77]:
x1 + y1

array([5, 7, 9])

In [78]:
2 * x1

array([2, 4, 6])

### ndarray

In [80]:
m = [1, 'abc', True]

In [81]:
m1 = np.array(m)

In [82]:
m1

array(['1', 'abc', 'True'], dtype='<U11')

In [85]:
m1.size

3

In [86]:
m1.shape

(3,)

In [87]:
m1.dtype

dtype('<U11')

In [88]:
k = (3, )

In [89]:
type(k)

tuple

In [90]:
j = (3)

In [91]:
type(j)

int

In [105]:
z = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [106]:
len(z)

3

In [108]:
z1 = np.array(z)

In [109]:
z1.size

9

In [110]:
z1.shape

(3, 3)

In [111]:
z1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
A = np.arange(25)

In [114]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [115]:
A.size

25

In [116]:
A.shape

(25,)

In [117]:
A.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [119]:
B = A.reshape(5, 5)

In [120]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### ufunc (Universal Functions)

In [121]:
import math

In [122]:
math.pi

3.141592653589793

In [123]:
math.sin(math.pi/2)

1.0

In [124]:
math.sin([math.pi/2, math.pi, math.pi*3/2])

TypeError: must be real number, not list

In [125]:
np.pi

3.141592653589793

In [126]:
np.sin(np.pi/2)

1.0

In [127]:
np.sin([np.pi/2, np.pi, np.pi*3/2])

array([ 1.0000000e+00,  1.2246468e-16, -1.0000000e+00])